name: Build and push docker image to GitHub Packages

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    name: Build and deploy latest image GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Log in to registry
        # This is where you will update the personal access token to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Get version
        run: echo "::set-output name=VERSION::$(git describe --tags --exact-match `git rev-parse HEAD`)"
        id: version

      - name: Build and push ui
        uses: docker/build-push-action@v4
        env:
          IMAGE_TAG: ${{ steps.version.outputs.VERSION }}
        with:
          context: ./ui
          platforms: linux/arm64, linux/amd64
          push: true
          tags: ghcr.io/rarimo/issuernode-ui:${{ env.IMAGE_TAG }}

      - name: Build and push amd64 image
        uses: docker/build-push-action@v4
        env:
          IMAGE_TAG: ${{ steps.version.outputs.VERSION }}
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/rarimo/issuernode:${{ env.IMAGE_TAG }}

      - name: Rename Docker Arm File
        run: |
          mv Dockerfile Dockerfile-amd
          mv Dockerfile-arm Dockerfile

      - name: Build and push arm64 image
        uses: docker/build-push-action@v4
        env:
          IMAGE_TAG: ${{ steps.version.outputs.VERSION }}
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ghcr.io/rarimo/issuernode-arm:${{ env.IMAGE_TAG }}